#!/usr/bin/env python3


from sys import argv

lines = []
for line in argv[1::]:
    lines.append(line)

bag = int(lines[0])

# Calcul du poids total
total = 0
for i in range(1, len(lines)):
    total += int(lines[i])

# Comparaison à la capacité du sac
if total <= bag:
    print("YES")
else:
    print("NO")
