#!/usr/bin/env python3


from sys import argv

lines = []
for line in argv[1::]:
    lines.append(line)

for i in range(int(lines[0])):
    lines_bis = lines[1 + 4 * i : 5 + 4 * i]
    A = list(map(float, lines_bis[0].split(" ")))
    B = list(map(float, lines_bis[1].split(" ")))
    C = list(map(float, lines_bis[2].split(" ")))
    M = list(map(float, lines_bis[3].split(" ")))

    # debug()

    if (B[0] - A[0]) * (C[0] - B[0]) + (B[1] - A[1]) * (C[1] - B[1]) > 0:
        MB = ((M[0] - B[0]) ** 2 + (M[1] - B[1]) ** 2) ** 0.5
        print(str(round(2 * MB, 6)))
        continue

    # First side :
    if A[0] == B[0]:
        M1 = [M[0] + 2 * (A[0] - M[0]), M[1]]

    elif A[1] == B[1]:
        M1 = [M[0], M[1] + 2 * (A[1] - M[1])]

    else:
        a = (A[1] - B[1]) / (A[0] - B[0])
        b = A[1] - a * A[0]
        U = [1, a]

        x = (U[0] * M[0] + U[1] * (2 * M[1] - a * M[0] - 2 * b)) / (U[0] + a * U[1])
        y = a * (M[0] + x) + 2 * b - M[1]
        M1 = [x, y]

    # Second side :
    if B[0] == C[0]:
        M2 = [M[0] + 2 * (B[0] - M[0]), M[1]]

    elif B[1] == C[1]:
        M2 = [M[0], M[1] + 2 * (B[1] - M[1])]

    else:
        a = (B[1] - C[1]) / (B[0] - C[0])
        b = B[1] - a * B[0]
        U = [1, a]

        x = (U[0] * M[0] + U[1] * (2 * M[1] - a * M[0] - 2 * b)) / (U[0] + a * U[1])
        y = a * (M[0] + x) + 2 * b - M[1]
        M2 = [x, y]

    print(str(round(((M1[0] - M2[0]) ** 2 + (M1[1] - M2[1]) ** 2) ** 0.5, 6)))
